/* eslint-disable no-unused-vars */

// message types
const types = {
    INFO_UPDATED: 'INFO_UPDATED',
    LOADING_START: 'LOADING_START',
    LOADING_ENDED: 'LOADING_ENDED',
    ALARM_UPDATE: 'ALARM_UPDATE',
    LOGIN: 'LOGIN',
    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGN_OUT: 'SIGN_OUT',
    RATE_EPISODE: 'RATE_EPISODE',
    UNCHECK_EPISODE: 'UNCHECK_EPISODE',
    EPISODE_WAS_RATED: 'EPISODE_WAS_RATED',
};

export default types;
