/* eslint-disable no-unused-vars */

// message types
const types = {
    INFO_UPDATED: 'INFO_UPDATED',
    LOADING_START: 'LOADING_START',
    LOADING_ENDED: 'LOADING_ENDED',
    ALARM_UPDATE: 'ALARM_UPDATE',
    SIGN_OUT: 'SIGN_OUT',
    RATE_EPISODE: 'RATE_EPISODE',
    UNCHECK_EPISODE: 'UNCHECK_EPISODE',
    EPISODE_WAS_RATED: 'EPISODE_WAS_RATED',
    RU_TITLES_UPDATE: 'RU_TITLES_UPDATE',
};
